# Generated by Django 6.0.7 on 2026-07-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('swatch_image', models.ImageField(blank=True, null=True, upload_to='fabric_swatches/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['extra_cost'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('before_image', models.ImageField(upload_to='gallery/before/')),
                ('after_image', models.ImageField(upload_to='gallery/after/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.fabricoption')),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('MORNING', 'Morning Drop-off'), ('EXPRESS', 'Same-Day 3-Hour Express'), ('AFTERNOON', 'Afternoon Drop-off')], default='MORNING', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'start_time', 'slot_type')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('damage_photo', models.ImageField(blank=True, null=True, upload_to='damage_photos/')),
                ('damage_description', models.TextField(blank=True)),
                ('service_mode', models.CharField(choices=[('DROP_OFF', 'Bring vehicle to shop'), ('PICK_UP', 'Request pick-up'), ('ON_SITE', 'On-site / mobile repair')], default='DROP_OFF', max_length=20)),
                ('location_notes', models.CharField(blank=True, help_text='Address/area for pick-up or on-site requests (e.g. suburb in Midrand).', max_length=255)),
                ('deposit_required', models.BooleanField(default=False)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.fabricoption')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.timeslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
