# Generated by Django 6.0.7 on 2026-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/before/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
