# Generated by Django 6.0.7 on 2026-07-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_galleryitem_before_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Sagging Roof Lining?', help_text='Main hero line (kept short — this is the big bold text).', max_length=120)),
                ('hero_heading_accent', models.CharField(default='Fixed Today.', help_text='Second part of the hero line, shown in the accent colour.', max_length=60)),
                ('hero_subheading', models.TextField(default='Trusted headliner & car roof lining repair in Midrand — book your slot online in under a minute, or message us on WhatsApp for an instant quote.')),
                ('hero_banner_image', models.ImageField(blank=True, help_text='Optional wide photo behind the hero section. If left blank, recent gallery photos are used instead.', null=True, upload_to='site_content/')),
                ('show_google_rating', models.BooleanField(default=True, help_text='Show the Google rating badge on the homepage.')),
                ('google_rating', models.DecimalField(decimal_places=1, default=4.9, help_text='e.g. 4.9 — update this to match your current Google Business rating.', max_digits=2)),
                ('google_review_count', models.PositiveIntegerField(default=0, help_text='Number of Google reviews behind the rating.')),
                ('google_review_url', models.URLField(blank=True, help_text='Optional: link straight to your Google reviews.')),
                ('about_heading', models.CharField(default='Why Midrand Trusts Us', max_length=120)),
                ('about_text', models.TextField(default="Years of hands-on craftsmanship, honest quotes, and a shop that actually picks up the phone. From sagging headliners to full interior refreshes, we treat every car like it's our own.")),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
