# Generated by Django 6.0.7 on 2026-07-26 19:32

import bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_sitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='damage_photo',
            field=models.ImageField(blank=True, null=True, upload_to='damage_photos/', validators=[bookings.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='fabricoption',
            name='swatch_image',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_swatches/', validators=[bookings.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='after_image',
            field=models.ImageField(upload_to='gallery/after/', validators=[bookings.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/before/', validators=[bookings.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/', validators=[bookings.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_banner_image',
            field=models.ImageField(blank=True, help_text='Optional wide photo behind the hero section. If left blank, recent gallery photos are used instead.', null=True, upload_to='site_content/', validators=[bookings.validators.validate_image_upload]),
        ),
    ]
