# Generated by Django 6.1.1 on 2026-09-15 11:52

import bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_damage_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='proof_of_payment',
            field=models.ImageField(blank=True, help_text='Screenshot of an EFT/bank transfer, if the customer paid a deposit that way.', null=True, upload_to='proof_of_payment/', validators=[bookings.validators.validate_image_upload]),
        ),
    ]
